error CS0246
 - warning MSB3245:
Could not resolve this reference. Could not locate the assembly "ResourceManager". Check to make sure the assembly exists on disk.
If this reference is required by your code, you may get compilation errors.
[...\src\GitExtensions.PluginTemplate\GitExtensions.PluginTemplate.csproj]

 - error CS0246: The type or namespace name 'GitUIPluginInterfaces' could not be found (are you missing a using directive or an assembly reference?)
[...\src\GitExtensions.PluginTemplate\GitExtensions.PluginTemplate.csproj]