error CS0012:
The type 'Image' is defined in an assembly that is not referenced.
You must add a reference to assembly 'System.Drawing.Common, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
[...\src\GitExtensions.PluginTemplate\GitExtensions.PluginTemplate.csproj]